[workspace]
members = [
    "backend",
    "entity",
    "frontend",
    "hub_bot",
    "migration",
    "service", "frontend",
]
resolver = "2"

[workspace.dependencies]
dotenv = "0.15.0"
serde_json = "1.0"

[workspace.dependencies.chrono]
version = "0.4"
features = ["serde"]

[workspace.dependencies.entity]
path = "entity"

[workspace.dependencies.migration]
path = "migration"

[workspace.dependencies.sea-orm]
version = "1.1.19"
features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "uuid",
    "chrono",
]

[workspace.dependencies.serde]
version = "1.0"
features = ["derive"]

[workspace.dependencies.tokio]
version = "1.40"
features = ["full"]

[workspace.dependencies.uuid]
version = "1.0"
features = [
    "v4",
    "serde",
]
