//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Hash)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "season_type")]
pub enum SeasonType {
    #[sea_orm(string_value = "season_type")]
    SeasonType,
    #[sea_orm(string_value = "Survivor")]
    Survivor,
    #[sea_orm(string_value = "Traitors")]
    Traitors,
    #[sea_orm(string_value = "BigBrother")]
    BigBrother,
    #[sea_orm(string_value = "TheChallenge")]
    TheChallenge,
    #[sea_orm(string_value = "Other")]
    Other,
}
