//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SeasonType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "season")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub org_id: Uuid,
    pub num_players: i32,
    pub start_date: Date,
    pub end_date: Option<Date>,
    pub season_type: SeasonType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::org::Entity",
        from = "Column::OrgId",
        to = "super::org::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Org,
    #[sea_orm(has_many = "super::season_member::Entity")]
    SeasonMember,
}

impl Related<super::org::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Org.def()
    }
}

impl Related<super::season_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeasonMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
