//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use sea_orm::Set;
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discord_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub discord_id: String,
    pub display_name: String,
    pub timezone: String,
    pub avatar_url: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::org::Entity")]
    Org,
}

impl Related<super::org::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Org.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl ActiveModel {
    pub fn new(discord_id: &str, display_name: &str, timezone: Option<String>, avatar_url: Option<String>) -> Self {
        Self {
            id: Set(Uuid::new_v4()),
            discord_id: Set(discord_id.to_string()),
            display_name: Set(display_name.to_string()),
            timezone: Set(timezone.unwrap_or_else(|| "UTC".to_string())),
            avatar_url: Set(avatar_url.unwrap_or_else(|| "".to_string())),
            created_at: Set(chrono::Utc::now().naive_utc()),
            updated_at: Set(chrono::Utc::now().naive_utc()),
        }
    }
}
